disabled_rules: # rule identifiers to exclude from running
 #- attributes
 #- closing_brace
 #- closure_end_indentation
 #- closure_parameter_position
 #- closure_spacing
 #- colon #71
 #- comma
 #- conditional_returns_on_newline
 # control_statement #1
 #- custom_rules
 #- cyclomatic_complexity
 #- dynamic_inline
 #- empty_count
 #- empty_parameters
 - empty_parentheses_with_trailing_closure #1
 #- explicit_init
 #- file_header
 #- file_length
 #- first_where
 #- force_cast #6
 #- force_try
 #- force_unwrapping
 #- function_body_length
 #- function_parameter_count
 #- implicit_getter
 #- leading_whitespace #1
 #- legacy_cggeometry_functions
 #- legacy_constant
 #- legacy_constructor
 #- legacy_nsgeometry_functions
 #- line_length #11
 #- mark
 #- missing_docs
 #- nesting
 #- nimble_operator
 #- number_separator
 #- opening_brace #3
 #- operator_usage_whitespace
 #- operator_whitespace #1
 #- overridden_super_call
 #- private_outlet
 #- private_unit_test
 #- prohibited_super_call
 #- redundant_nil_coalescing
 #- redundant_string_enum_value
 #- return_arrow_whitespace
 #- statement_position #6
 #- switch_case_on_newline
 #- syntactic_sugar
 #- todo #1
 #- trailing_comma
 #- trailing_newline
 #- trailing_semicolon
 - trailing_whitespace #246
 #- type_body_length
 #- type_name
 - unused_closure_parameter #13
 #- unused_enumerated
 - valid_docs
 #- valid_ibinspectable
 # - variable_name #2
 - vertical_whitespace #1
 #- void_return #8
 #- weak_delegate

opt_in_rules:
  force_unwrapping
  prohibited_super_call
  redundant_nil_coalescing
  nimble_operator

variable_name:
  max_length: 45
  min_length: 2

line_length: 120

included:
  - spacex
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - spacex/Classes/Mocks/GeneratedMocks.swift
#   - Pods
#   - Legacy
#   - Dependencies

custom_rules:
  header_boilerplate:
    name: "File header boilerplate"
    regex: "Copyright"
    match_kinds:
      - comment
    message: "Please remove the file comment boilerplate."
